# Generated by Django 4.1.5 on 2023-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
